CREATE TABLE data_opc_r2 (
id INT AUTO_INCREMENT PRIMARY KEY,
sample_time DATETIME NOT NULL,
serial_number VARCHAR(50) NOT NULL,
pm1 DECIMAL(10,1) NOT NULL,
pm2_5 DECIMAL(10,1) NOT NULL,
pm10 DECIMAL(10,1) NOT NULL
);

CREATE TABLE data_pms5003 (
id INT AUTO_INCREMENT PRIMARY KEY,
sample_time DATETIME NOT NULL,
serial_number VARCHAR(32) NOT NULL,
pm1 INT NOT NULL,
pm2_5 INT NOT NULL,
pm10 INT NOT NULL,
pn0_3 INT NOT NULL,
pn0_5 INT NOT NULL,
pn1 INT NOT NULL,
pn2_5 INT NOT NULL,
pn5 INT NOT NULL,
pn10 INT NOT NULL
);